version: "3.8"
services:
  app-backend:
    container_name: node_app
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - ./path-to-backend-directory:/usr/src/app
      - /usr/src/app/node_modules
  app-frontend:
    container_name: react_app
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./path-to-frontend-directory:/usr/src/app
      - /usr/src/app/node_modules
  db:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
